require_dependency 'controllers/plm_clipboard'
require_dependency 'controllers/plm_event'
require_dependency 'controllers/plm_lifecycle'
require_dependency 'controllers/plm_modeling'
require_dependency 'controllers/plm_tree_items'
require_dependency 'controllers/plm_tree'
require_dependency 'controllers/tree_actions_by_roles'
require_dependency 'controllers/plm_table'