Access.create([
{"id"=>1, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumItemsController", "action"=>"create"},
{"id"=>2, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumItemsController", "action"=>"destroy"},
{"id"=>3, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumItemsController", "action"=>"edit"},
{"id"=>4, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumItemsController", "action"=>"new"},
{"id"=>5, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumItemsController", "action"=>"update"},
{"id"=>6, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DatafilesController", "action"=>"create"},
{"id"=>7, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DatafilesController", "action"=>"destroy"},
{"id"=>8, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DatafilesController", "action"=>"download_file"},
{"id"=>9, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DatafilesController", "action"=>"edit"},
{"id"=>10, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DatafilesController", "action"=>"new"},
{"id"=>11, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DatafilesController", "action"=>"show_file"},
{"id"=>12, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DatafilesController", "action"=>"update"},
{"id"=>13, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesUsersController", "action"=>"create"},
{"id"=>14, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesUsersController", "action"=>"destroy"},
{"id"=>15, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesUsersController", "action"=>"edit"},
{"id"=>16, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesUsersController", "action"=>"new"},
{"id"=>17, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesUsersController", "action"=>"show"},
{"id"=>18, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesUsersController", "action"=>"update"},
{"id"=>19, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"SequencesController", "action"=>"create"},
{"id"=>20, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"SequencesController", "action"=>"destroy"},
{"id"=>21, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"SequencesController", "action"=>"edit"},
{"id"=>22, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"SequencesController", "action"=>"new"},
{"id"=>23, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"SequencesController", "action"=>"show"},
{"id"=>24, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"SequencesController", "action"=>"update"},
{"id"=>25, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"add_docs"},
{"id"=>26, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"add_forum"},
{"id"=>27, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"add_parts"},
{"id"=>28, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"add_users"},
{"id"=>29, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"create"},
{"id"=>30, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"demote"},
{"id"=>31, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"destroy"},
{"id"=>32, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"edit"},
{"id"=>33, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"new"},
{"id"=>34, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"new_forum"},
{"id"=>35, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"promote"},
{"id"=>36, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProjectsController", "action"=>"update"},
{"id"=>37, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ExpressionsController", "action"=>"destroy"},
{"id"=>38, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ExpressionsController", "action"=>"show_tree"},
{"id"=>39, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ExpressionsController", "action"=>"update"},
{"id"=>40, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ExpressionsController", "action"=>"update_tree"},
{"id"=>41, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DefinitionsController", "action"=>"create"},
{"id"=>42, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DefinitionsController", "action"=>"destroy"},
{"id"=>43, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DefinitionsController", "action"=>"edit"},
{"id"=>44, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DefinitionsController", "action"=>"new"},
{"id"=>45, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DefinitionsController", "action"=>"new_process"},
{"id"=>46, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DefinitionsController", "action"=>"tree"},
{"id"=>47, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DefinitionsController", "action"=>"update"},
{"id"=>48, "roles"=>"admin | creator | analyst | designer | valider | project_manager | consultant", "controller"=>"SessionsController", "action"=>"activate"},
{"id"=>49, "roles"=>"admin | creator | analyst | designer | valider | project_manager | consultant", "controller"=>"SessionsController", "action"=>"create"},
{"id"=>50, "roles"=>"admin | creator | analyst | designer | valider | project_manager | consultant", "controller"=>"SessionsController", "action"=>"create_new_account"},
{"id"=>51, "roles"=>"admin | creator | analyst | designer | valider | project_manager | consultant", "controller"=>"SessionsController", "action"=>"destroy"},
{"id"=>52, "roles"=>"admin | creator | analyst | designer | valider | project_manager | consultant", "controller"=>"SessionsController", "action"=>"edit"},
{"id"=>53, "roles"=>"admin | creator | analyst | designer | valider | project_manager | consultant", "controller"=>"SessionsController", "action"=>"login"},
{"id"=>54, "roles"=>"admin | creator | analyst | designer | valider | project_manager | consultant", "controller"=>"SessionsController", "action"=>"new"},
{"id"=>55, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ChecksController", "action"=>"create"},
{"id"=>56, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ChecksController", "action"=>"destroy"},
{"id"=>57, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ChecksController", "action"=>"edit"},
{"id"=>58, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ChecksController", "action"=>"new"},
{"id"=>59, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ChecksController", "action"=>"update"},
{"id"=>60, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ViewsController", "action"=>"create"},
{"id"=>61, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ViewsController", "action"=>"destroy"},
{"id"=>62, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ViewsController", "action"=>"edit"},
{"id"=>63, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ViewsController", "action"=>"new"},
{"id"=>64, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ViewsController", "action"=>"update"},
{"id"=>65, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"QuestionsController", "action"=>"edit"},
{"id"=>66, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesController", "action"=>"create"},
{"id"=>67, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesController", "action"=>"destroy"},
{"id"=>68, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesController", "action"=>"edit"},
{"id"=>69, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesController", "action"=>"new"},
{"id"=>70, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesController", "action"=>"show"},
{"id"=>71, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"RolesController", "action"=>"update"},
{"id"=>72, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"WorkitemsController", "action"=>"destroy"},
{"id"=>73, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"WorkitemsController", "action"=>"edit"},
{"id"=>74, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"WorkitemsController", "action"=>"show"},
{"id"=>75, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"WorkitemsController", "action"=>"update"},
{"id"=>76, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UsersController", "action"=>"create"},
{"id"=>77, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UsersController", "action"=>"destroy"},
{"id"=>78, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UsersController", "action"=>"edit"},
{"id"=>79, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UsersController", "action"=>"edit_password"},
{"id"=>80, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UsersController", "action"=>"new"},
{"id"=>81, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UsersController", "action"=>"update"},
{"id"=>82, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UsersController", "action"=>"update_password"},
{"id"=>83, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"NotificationsController", "action"=>"create"},
{"id"=>84, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"NotificationsController", "action"=>"destroy"},
{"id"=>85, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"NotificationsController", "action"=>"edit"},
{"id"=>86, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"NotificationsController", "action"=>"new"},
{"id"=>87, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"NotificationsController", "action"=>"notify"},
{"id"=>88, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"NotificationsController", "action"=>"update"},
{"id"=>89, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumsController", "action"=>"create"},
{"id"=>90, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumsController", "action"=>"destroy"},
{"id"=>91, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumsController", "action"=>"edit"},
{"id"=>92, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumsController", "action"=>"new"},
{"id"=>93, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ForumsController", "action"=>"update"},
{"id"=>94, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"RelationsController", "action"=>"create"},
{"id"=>95, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"RelationsController", "action"=>"destroy"},
{"id"=>96, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"RelationsController", "action"=>"edit"},
{"id"=>97, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"RelationsController", "action"=>"new"},
{"id"=>98, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"RelationsController", "action"=>"update"},
{"id"=>99, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"RelationsController", "action"=>"update_child"},
{"id"=>100, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"RelationsController", "action"=>"update_father"},
{"id"=>101, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"GroupDefinitionsController", "action"=>"create"},
{"id"=>102, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"GroupDefinitionsController", "action"=>"destroy"},
{"id"=>103, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"TypesobjectsController", "action"=>"create"},
{"id"=>104, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"TypesobjectsController", "action"=>"destroy"},
{"id"=>105, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"TypesobjectsController", "action"=>"edit"},
{"id"=>106, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"TypesobjectsController", "action"=>"new"},
{"id"=>107, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"TypesobjectsController", "action"=>"update"},
{"id"=>108, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"create"},
{"id"=>109, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"destroy"},
{"id"=>110, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"edit"},
{"id"=>111, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"edit_in_tree"},
{"id"=>112, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"new"},
{"id"=>113, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"remove_link"},
{"id"=>114, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"reset"},
{"id"=>115, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"LinksController", "action"=>"update"},
{"id"=>116, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"StatusobjectsController", "action"=>"create"},
{"id"=>117, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"StatusobjectsController", "action"=>"destroy"},
{"id"=>118, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"StatusobjectsController", "action"=>"edit"},
{"id"=>119, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"StatusobjectsController", "action"=>"new"},
{"id"=>120, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"StatusobjectsController", "action"=>"update"},
{"id"=>121, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"VolumesController", "action"=>"create"},
{"id"=>122, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"VolumesController", "action"=>"destroy"},
{"id"=>123, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"VolumesController", "action"=>"edit"},
{"id"=>124, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"VolumesController", "action"=>"new"},
{"id"=>125, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"VolumesController", "action"=>"update"},
{"id"=>126, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"add_docs"},
{"id"=>127, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"add_forum"},
{"id"=>128, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"add_projects"},
{"id"=>129, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"create"},
{"id"=>130, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"demote"},
{"id"=>131, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"destroy"},
{"id"=>132, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"edit"},
{"id"=>133, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"new"},
{"id"=>134, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"new_forum"},
{"id"=>135, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"promote"},
{"id"=>136, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"CustomersController", "action"=>"update"},
{"id"=>137, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ErrorsController", "action"=>"destroy"},
{"id"=>138, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UserGroupsController", "action"=>"create"},
{"id"=>139, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"UserGroupsController", "action"=>"destroy"},
{"id"=>140, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProcessesController", "action"=>"create"},
{"id"=>141, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProcessesController", "action"=>"destroy"},
{"id"=>142, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProcessesController", "action"=>"new"},
{"id"=>143, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"ProcessesController", "action"=>"tree"},
{"id"=>144, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"GroupsController", "action"=>"create"},
{"id"=>145, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"GroupsController", "action"=>"destroy"},
{"id"=>146, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"GroupsController", "action"=>"edit"},
{"id"=>147, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"GroupsController", "action"=>"new"},
{"id"=>148, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"GroupsController", "action"=>"update"},
{"id"=>149, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"add_docs"},
{"id"=>150, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"add_forum"},
{"id"=>151, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"add_parts"},
{"id"=>152, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"create"},
{"id"=>153, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"demote"},
{"id"=>154, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"destroy"},
{"id"=>155, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"edit"},
{"id"=>156, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"new"},
{"id"=>157, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"new_forum"},
{"id"=>158, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"promote"},
{"id"=>159, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"revise"},
{"id"=>160, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"PartsController", "action"=>"update"},
{"id"=>161, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"InfoController", "action"=>"which_documents"},
{"id"=>162, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"add_datafile"},
{"id"=>163, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"add_docs"},
{"id"=>164, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"check_free"},
{"id"=>165, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"check_in"},
{"id"=>166, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"check_out"},
{"id"=>167, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"create"},
{"id"=>168, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"demote"},
{"id"=>169, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"destroy"},
{"id"=>170, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"edit"},
{"id"=>171, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"new"},
{"id"=>172, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"new_datafile"},
{"id"=>173, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"promote"},
{"id"=>174, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"revise"},
{"id"=>175, "roles"=>"(admin | creator | analyst | designer | valider | project_manager) & (!consultant)", "controller"=>"DocumentsController", "action"=>"update"},
{"id"=>176, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"AccessesController", "action"=>"create"},
{"id"=>177, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"AccessesController", "action"=>"destroy"},
{"id"=>178, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"AccessesController", "action"=>"edit"},
{"id"=>179, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"AccessesController", "action"=>"new"},
{"id"=>180, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"AccessesController", "action"=>"reset"},
{"id"=>181, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"AccessesController", "action"=>"show"},
{"id"=>182, "roles"=>"admin& (!consultant!!creator | !analyst | !designer | !valider | !project_manager)", "controller"=>"AccessesController", "action"=>"update"}])
Role.create([
{"id"=>1, "title"=>"admin", "description"=>"Administrateur", "internal"=>true},
{"id"=>2, "title"=>"consultant", "description"=>"Peut voir les donnees sans pouvoir les modifier", "internal"=>true},
{"id"=>3, "title"=>"creator", "description"=>"Ecrit les specifications des produits", "internal"=>true},
{"id"=>101, "title"=>"analyst", "description"=>"\"Effectue des etudes de marche et ecrit le cdc.\nElabore l'expression de besoin.\"\n", "internal"=>true},
{"id"=>102, "title"=>"designer", "description"=>"Modelise les produits", "internal"=>true},
{"id"=>103, "title"=>"valider", "description"=>"Valide les processus du cycle de vie des donnees", "internal"=>true},
{"id"=>104, "title"=>"project_manager", "description"=>"Responsable du planning, des ressources", "internal"=>true}])
Project.create([
{"id"=>1, "owner_id"=>1, "typesobject_id"=>997141214, "statusobject_id"=>10, "ident"=>"PROJECT-admin", "designation"=>"Projet par defaut pour l'administrateur", "date"=>"2012-03-14", "group_id"=>1, "typeaccess_id"=>7, "internal"=>true}])
Relation.create([
{"id"=>104805023, "name"=>"describe_by", "type_id"=>"749051069", "father_plmtype"=>"any_plmtype", "child_plmtype"=>"document", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>125139104, "name"=>"any_relation", "type_id"=>"413872662", "father_plmtype"=>"any_plmtype", "child_plmtype"=>"any_plmtype", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>330870412, "name"=>"hierarchic_to", "type_id"=>"905287875", "father_plmtype"=>"customer", "child_plmtype"=>"customer", "father_type_id"=>141, "child_type_id"=>141, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>447638310, "name"=>"modify_by", "type_id"=>"989626521", "father_plmtype"=>"any_plmtype", "child_plmtype"=>"document", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>453977618, "name"=>"link_doc", "type_id"=>"262221517", "father_plmtype"=>"document", "child_plmtype"=>"document", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>533675056, "name"=>"contains", "type_id"=>"913245371", "father_plmtype"=>"project", "child_plmtype"=>"part", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>644429538, "name"=>"ask_for", "type_id"=>"672869653", "father_plmtype"=>"customer", "child_plmtype"=>"project", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>1, "cardin_use_min"=>0, "cardin_use_max"=>2},
{"id"=>747117003, "name"=>"applicable", "type_id"=>"382640329", "father_plmtype"=>"history_entry", "child_plmtype"=>"any_plmtype", "father_type_id"=>12, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>986750168, "name"=>"discuss_by", "type_id"=>"841581186", "father_plmtype"=>"any_plmtype", "child_plmtype"=>"forum", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>1027996074, "name"=>"bom_part", "type_id"=>"291198241", "father_plmtype"=>"part", "child_plmtype"=>"part", "father_type_id"=>5, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1},
{"id"=>1062605010, "name"=>"reference", "type_id"=>"382640329", "father_plmtype"=>"history_entry", "child_plmtype"=>"any_plmtype", "father_type_id"=>12, "child_type_id"=>5, "cardin_occur_min"=>0, "cardin_occur_max"=>-1, "cardin_use_min"=>0, "cardin_use_max"=>-1}])
Statusobject.create([
{"id"=>4, "object"=>"document", "name"=>"inwork", "rank"=>1, "promote_id"=>2, "demote_id"=>0},
{"id"=>5, "object"=>"document", "name"=>"ready", "rank"=>2, "promote_id"=>3, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>6, "object"=>"document", "name"=>"approved", "rank"=>3, "promote_id"=>0, "demote_id"=>0, "description"=>"Pret pour la validation"},
{"id"=>7, "object"=>"part", "name"=>"inprogress", "rank"=>1, "promote_id"=>2, "demote_id"=>0, "description"=>"Pret pour la validation"},
{"id"=>8, "object"=>"part", "name"=>"ready", "rank"=>2, "promote_id"=>3, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>9, "object"=>"part", "name"=>"validated", "rank"=>3, "promote_id"=>0, "demote_id"=>0, "description"=>"Pret pour la validation"},
{"id"=>10, "object"=>"project", "name"=>"started", "rank"=>1, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>11, "object"=>"project", "name"=>"finished", "rank"=>2, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>12, "object"=>"project", "name"=>"hasbeen", "rank"=>3, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>13, "object"=>"forum", "name"=>"open", "rank"=>1, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>14, "object"=>"forum", "name"=>"close", "rank"=>2, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>21, "object"=>"customer", "name"=>"active", "rank"=>1, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>22, "object"=>"customer", "name"=>"inactive", "rank"=>2, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"},
{"id"=>23, "object"=>"customer", "name"=>"hasbeen", "rank"=>3, "promote_id"=>1, "demote_id"=>1, "description"=>"Pret pour la validation"}])
Role.find(1) << User.find(1)
Role.find(2) << User.find(101)
Role.find(2) << User.find(102)
Role.find(2) << User.find(103)
Role.find(2) << User.find(104)
Role.find(2) << User.find(105)
Role.find(2) << User.find(106)
Role.find(2) << User.find(107)
User.create([
{"id"=>1, "email"=>"sylvere.coutable@laposte.net", "login"=>"admin", "first_name"=>"", "last_name"=>"", "language"=>"fr", "time_zone"=>"", "theme"=>"blackwhite", "hashed_password"=>"a1730405a15d17e73c9e962f9f0bf1f456b973b8", "salt"=>"1234", "volume_id"=>1, "nb_items"=>200, "notification"=>0, "show_mail"=>false, "typesobject_id"=>3, "internal"=>true},
{"id"=>101, "email"=>"sylvere.coutable@laposte.net", "login"=>"syl", "first_name"=>"", "last_name"=>"", "language"=>"fr", "time_zone"=>"", "theme"=>"blackwhite", "hashed_password"=>"98f7177b50203d053df24f153712229a23030f2e", "salt"=>"1234", "volume_id"=>1, "nb_items"=>200, "notification"=>0, "show_mail"=>false, "typesobject_id"=>3, "internal"=>true},
{"id"=>102, "email"=>"alice@example.com", "login"=>"alice", "first_name"=>"", "last_name"=>"", "language"=>"fr", "time_zone"=>"", "theme"=>"blackwhite", "hashed_password"=>"8e75d5d0e60f6893ffda3a6fd03716f738c56748", "salt"=>"1234", "volume_id"=>1, "nb_items"=>200, "notification"=>0, "show_mail"=>false, "typesobject_id"=>3, "internal"=>true},
{"id"=>103, "email"=>"bob@example.com", "login"=>"bob", "first_name"=>"", "last_name"=>"", "language"=>"fr", "time_zone"=>"", "theme"=>"blackwhite", "hashed_password"=>"45baf464fcf9f445919555197cbbce1516146106", "salt"=>"1234", "volume_id"=>1, "nb_items"=>1000, "notification"=>0, "show_mail"=>false, "typesobject_id"=>3, "internal"=>true},
{"id"=>104, "email"=>"charly@example.com", "login"=>"charly", "first_name"=>"", "last_name"=>"", "language"=>"fr", "time_zone"=>"", "theme"=>"blackwhite", "hashed_password"=>"ae41ca2ce64f955ae2000c50c0654a083a64f578", "salt"=>"1234", "volume_id"=>1, "nb_items"=>1000, "notification"=>0, "show_mail"=>false, "typesobject_id"=>3, "internal"=>true},
{"id"=>105, "email"=>"robert@example.com", "login"=>"robert", "first_name"=>"Robert", "last_name"=>"Maxwell", "language"=>"fr", "time_zone"=>"Paris", "theme"=>"blackwhite", "hashed_password"=>"acf828308f24af131e59c84d0cf2ee8b65111a73", "salt"=>"1234", "volume_id"=>1, "nb_items"=>1000, "notification"=>1, "show_mail"=>false, "typesobject_id"=>3, "internal"=>true},
{"id"=>106, "email"=>"sylvia@example.com", "login"=>"sylvia", "first_name"=>"", "last_name"=>"", "language"=>"fr", "time_zone"=>"", "theme"=>"blackwhite", "hashed_password"=>"851099f53bb9ca407186cef1e665b2fd4c9da822", "salt"=>"1234", "volume_id"=>1, "nb_items"=>1000, "notification"=>1, "show_mail"=>true, "typesobject_id"=>3, "internal"=>true},
{"id"=>107, "email"=>"peter@example.com", "login"=>"peter", "first_name"=>"", "last_name"=>"", "language"=>"fr", "time_zone"=>"", "theme"=>"blackwhite", "hashed_password"=>"d53e167030805511f46ee272cdfbc9b76f379447", "salt"=>"1234", "volume_id"=>1, "nb_items"=>1000, "notification"=>1, "show_mail"=>false, "typesobject_id"=>3, "internal"=>true}])
Sequence.create([
{"id"=>1, "value"=>"DOC000000", "utility"=>"Document.ident", "modify"=>false, "sequence"=>true},
{"id"=>2, "value"=>"PRT000000", "utility"=>"Part.ident", "modify"=>false, "sequence"=>true},
{"id"=>3, "value"=>"PROJET", "utility"=>"Project.ident", "modify"=>true, "sequence"=>false},
{"id"=>4, "value"=>"CUSTOMER", "utility"=>"Customer.ident", "modify"=>true, "sequence"=>false},
{"id"=>5, "value"=>"Designation document", "utility"=>"Document.designation", "modify"=>true, "sequence"=>false},
{"id"=>6, "value"=>"Designation article", "utility"=>"Part.designation", "modify"=>true, "sequence"=>false},
{"id"=>7, "value"=>"Designation projet", "utility"=>"Project.designation", "modify"=>true, "sequence"=>false},
{"id"=>8, "value"=>"Designation client", "utility"=>"Customer.designation", "modify"=>true, "sequence"=>false},
{"id"=>9, "value"=>"0", "utility"=>"Document.revision", "modify"=>false, "sequence"=>false},
{"id"=>10, "value"=>"AAA", "utility"=>"Part.revision", "modify"=>false, "sequence"=>false},
{"id"=>20, "value"=>"DF0000000000", "utility"=>"Datafile.ident", "modify"=>false, "sequence"=>true},
{"id"=>21, "value"=>"0", "utility"=>"Relation.cardin_occur_min", "modify"=>false, "sequence"=>false},
{"id"=>22, "value"=>"-1", "utility"=>"Relation.cardin_occur_max", "modify"=>false, "sequence"=>false},
{"id"=>23, "value"=>"0", "utility"=>"Relation.cardin_use_min", "modify"=>false, "sequence"=>false},
{"id"=>24, "value"=>"-1", "utility"=>"Relation.cardin_use_max", "modify"=>false, "sequence"=>false},
{"id"=>31, "value"=>"local_vault", "utility"=>"Volume.protocol", "modify"=>false, "sequence"=>false}])
Volume.create([
{"id"=>1, "name"=>"vol_fog_01", "protocol"=>"fog", "description"=>"volume de depart sur fog", "internal"=>true},
{"id"=>2, "name"=>"vol_local_01", "protocol"=>"file_system", "description"=>"volume en local sur le serveur", "internal"=>true}])
Group.create([
{"id"=>1, "name"=>"admins", "internal"=>true},
{"id"=>2, "name"=>"consultants", "internal"=>true},
{"id"=>3, "name"=>"creators", "internal"=>true},
{"id"=>4, "name"=>"validers", "internal"=>true},
{"id"=>101, "name"=>"marketing", "internal"=>true},
{"id"=>102, "name"=>"SICM", "internal"=>true},
{"id"=>103, "name"=>"BE", "internal"=>true},
{"id"=>104, "name"=>"BM", "internal"=>true}])
Group.find(1) << Definition.find(1)
Group.find(1) << Definition.find(2)
Group.find(2) << Definition.find(3)
Group.find(2) << Definition.find(4)
Group.find(2) << Definition.find(5)
Group.find(1) << Definition.find(3)
Group.find(1) << Definition.find(6)
Group.find(1) << Definition.find(4)
Group.find(1) << Definition.find(7)
Group.find(2) << Definition.find(7)
Typesobject.create([
{"id"=>1, "object"=>"user", "name"=>"$NEW_ACCOUNT", "description"=>"Type donn\xC3\xA9 au compte \xC3\xA0 sa cr\xC3\xA9ation, en attendant sa validation.", "internal"=>true},
{"id"=>2, "object"=>"project", "name"=>"$PROJ_ACCOUNT", "description"=>"Type de projet affect\xC3\xA9 automatiquement \xC3\xA0 la cr\xC3\xA9ation du compte.", "internal"=>true},
{"id"=>3, "object"=>"user", "name"=>"person_", "description"=>"Personne physique.", "internal"=>true},
{"id"=>4, "object"=>"user", "name"=>"virtual_", "description"=>"Utilisateur virtuel, pour les batchs ...", "internal"=>true},
{"id"=>41165346, "object"=>"history_entry", "name"=>"history_entry", "description"=>"Historique de processus", "internal"=>true},
{"id"=>138668910, "object"=>"project_typeaccess", "name"=>"confidential", "description"=>"Projet confidentiel", "internal"=>true},
{"id"=>258446918, "object"=>"project_typeaccess", "name"=>"secret", "description"=>"Projet secret", "internal"=>true},
{"id"=>262221517, "object"=>"relation", "name"=>"document_document", "description"=>"Projet secret", "internal"=>true},
{"id"=>291198241, "object"=>"relation", "name"=>"part_part", "description"=>"Projet secret", "internal"=>true},
{"id"=>382640329, "object"=>"relation", "name"=>"history_entry", "description"=>"Projet secret", "internal"=>true},
{"id"=>413872662, "object"=>"relation", "name"=>"any_relation_type", "description"=>"Relation g\xC3\xA9n\xC3\xA9rique", "internal"=>true},
{"id"=>473241593, "object"=>"any_plmtype", "name"=>"any_type", "description"=>"Type g\xC3\xA9n\xC3\xA9rique", "internal"=>true},
{"id"=>502955464, "object"=>"relation", "name"=>"document_forum", "description"=>"Type g\xC3\xA9n\xC3\xA9rique", "internal"=>true},
{"id"=>598687896, "object"=>"ar_workitem", "name"=>"ar_workitem", "description"=>"Tache de processus", "internal"=>true},
{"id"=>672869653, "object"=>"relation", "name"=>"customer_project", "description"=>"Tache de processus", "internal"=>true},
{"id"=>678514879, "object"=>"project_typeaccess", "name"=>"public", "description"=>"Projet public", "internal"=>true},
{"id"=>728513243, "object"=>"relation", "name"=>"part_document", "description"=>"Projet public", "internal"=>true},
{"id"=>749051069, "object"=>"relation", "name"=>"customer_document", "description"=>"Projet public", "internal"=>true},
{"id"=>841581186, "object"=>"relation", "name"=>"project_forum", "description"=>"Projet public", "internal"=>true},
{"id"=>905287875, "object"=>"relation", "name"=>"customer_customer", "description"=>"Projet public", "internal"=>true},
{"id"=>913245371, "object"=>"relation", "name"=>"project_part", "description"=>"Projet public", "internal"=>true},
{"id"=>980319875, "object"=>"relation", "name"=>"customer_forum", "description"=>"Projet public", "internal"=>true},
{"id"=>989626521, "object"=>"relation", "name"=>"part_forum", "description"=>"Projet public", "internal"=>true},
{"id"=>1045584111, "object"=>"relation", "name"=>"project_document", "description"=>"Projet public", "internal"=>true}])
Definition.create([
{"id"=>1, "name"=>"*embedded*", "description"=>"the right to start processes embedded in launch items", "internal"=>true},
{"id"=>2, "name"=>"*untracked*", "description"=>"the right to launch processes from any URI", "internal"=>true},
{"id"=>3, "name"=>"simple sequence", "description"=>"a simple sequence", "internal"=>true, "uri"=>"sequence1.rb"},
{"id"=>4, "name"=>"leave request", "description"=>"may I leave the office ?", "internal"=>true, "uri"=>"leave_request1.rb", "launch_fields"=>"{\"employee\":\"\",\"from_date\":\"\",\"to_date\":\"\",\"reason\":\"\"}"},
{"id"=>5, "name"=>"revision", "description"=>"Revision d un objet PLM", "internal"=>true, "uri"=>"/definitions/revise.rb", "launch_fields"=>"{}"},
{"id"=>6, "name"=>"promotion", "description"=>"Promotion d un objet PLM", "internal"=>true, "uri"=>"/definitions/promote.rb", "launch_fields"=>"{}"}])
User.find(1) << Group.find(1)
User.find(1) << Group.find(2)
User.find(1) << Group.find(3)
User.find(1) << Group.find(4)
User.find(1) << Group.find(101)
User.find(1) << Group.find(102)
User.find(1) << Group.find(103)
User.find(1) << Group.find(104)
User.find(101) << Group.find(2)
User.find(101) << Group.find(3)
User.find(101) << Group.find(4)
User.find(102) << Group.find(2)
User.find(103) << Group.find(2)
User.find(104) << Group.find(2)
User.find(105) << Group.find(2)
User.find(106) << Group.find(2)
User.find(107) << Group.find(2)
